In [1]:
import numpy as np

In [4]:
a = np.arange(15).reshape(3, 5)
%time

Wall time: 0 ns


In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8])

In [14]:
b

array([6, 7, 8])

In [15]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
b = np.array([6, 7, 8])

In [17]:
a = np.array([2,3,4])

In [18]:
a

array([2, 3, 4])

In [19]:
a.dtype

dtype('int32')

In [20]:
b = np.array([1.2, 3.5, 5.1])

In [21]:
b

array([1.2, 3.5, 5.1])

In [22]:
b.dtype

dtype('float64')

In [1]:
print(np.__version__)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.18.1


In [4]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
a = np.ones((3,3), dtype=bool)

In [7]:
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [10]:
arr[arr % 3 == 1]

array([1, 4, 7])

In [11]:
arr[arr == 1]

array([1])

In [12]:
arr[arr > 5]

array([6, 7, 8, 9])

In [13]:
arr[arr % 2 == 1] = -1

In [14]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
arr = np.arange(10)

In [16]:
out = np.where(arr % 2 == 1, -1, arr)

In [17]:
out = np.where(arr % 2 == 1, -1, arr)
%time

Wall time: 0 ns


In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
arr = np.arange(10)
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
arr = np.arange(10)
arr.reshape(2, 4)

ValueError: cannot reshape array of size 10 into shape (2,4)

In [22]:
arr = np.arange(10)
arr.reshape(2, 6)

ValueError: cannot reshape array of size 10 into shape (2,6)

In [23]:
a = np.arange(10).reshape(2,-1)

In [24]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
b = np.repeat(1, 10).reshape(2,-1)

In [26]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
# Stacking up the arrays a and b
# Method 1
np.concatenate([a, b], axis=0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
# Stacking up the arrays a and b
# Method 2
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
# Stacking up the arrays a and b
# Method 3
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# Stacking up the arrays a and b horizontally
# Method 1
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [32]:
# Stacking up the arrays a and b horizontally
# Method 2
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [34]:
# Stacking up the arrays a and b horizontally
# Method 3
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [36]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
a = np.array([1,2,3])`

SyntaxError: invalid syntax (<ipython-input-37-3982170e969a>, line 1)

In [38]:
a = np.array([1,2,3])

In [41]:
firstPart = np.repeat(a, 3)

In [42]:
secondPart = np.tile(a, 3)

In [43]:
np.r_[firstPart, secondPart]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6,12])
b = np.array([7,2,10,2,7,4,9,4,9,8,12])

In [45]:
# Common Items among 2 arrays

In [51]:
np.intersect1d(a,b)

array([ 2,  4, 12])

In [52]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [53]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [54]:
np.setdiff1d(b,a)

array([6, 7, 8, 9])

In [55]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [56]:
a = np.arange(15)

In [57]:
# Method 1
index = np.where((a >= 5) & (a <= 10))

In [58]:
index

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

In [59]:
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [61]:
index = np.where((a >= 5) & (a <= 10))

In [62]:
index

(array([1, 3, 4], dtype=int64),)

In [63]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [64]:
index = np.where((a >= 5) & (a <= 10))

In [65]:
a[index]

array([ 6,  9, 10])

In [66]:
# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [67]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [68]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [69]:
maxx(3,3)

3

In [70]:
maxx(8, 9)

9

In [71]:
pair_max = np.vectorize(maxx, otypes=[float])

In [72]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [73]:
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [74]:
pair_max(a, b)
%time

Wall time: 0 ns


In [75]:
arr = np.arange(9).reshape(3,3)

In [76]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [78]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
arr[:, [1,1,2]]

array([[1, 1, 2],
       [4, 4, 5],
       [7, 7, 8]])

In [80]:
arr[:, [1,1,1]]

array([[1, 1, 1],
       [4, 4, 4],
       [7, 7, 7]])

In [81]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
arr = np.arange(9).reshape(3,3)

In [83]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
arr[:, [2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [85]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [86]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
arr[[2,1,0], :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [89]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [90]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [94]:
arr = np.arange(9).reshape(3,3)

In [95]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
np.random.random((5,3)

SyntaxError: unexpected EOF while parsing (<ipython-input-96-9c5a0e39fa2c>, line 1)

In [97]:
np.random.random(5,3)

TypeError: random() takes at most 1 positional argument (2 given)

In [98]:
np.random.randint(low=5, high=10, size=(5,3))

array([[7, 6, 8],
       [8, 7, 5],
       [9, 8, 6],
       [7, 9, 6],
       [5, 8, 6]])

In [99]:
np.random.randint(low=5, high=10, size=(5,3))

array([[5, 7, 5],
       [5, 8, 8],
       [7, 9, 6],
       [7, 5, 7],
       [6, 8, 7]])

In [100]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

In [101]:
rand_arr

array([[5.9301204 , 7.22184479, 5.82927701],
       [5.06744839, 8.9135278 , 6.17543541],
       [7.99424462, 7.43102964, 8.31444955],
       [5.11718415, 6.15920666, 7.50399828],
       [8.35862899, 6.89774308, 9.47737575]])

In [102]:
rand_arr

array([[5.9301204 , 7.22184479, 5.82927701],
       [5.06744839, 8.9135278 , 6.17543541],
       [7.99424462, 7.43102964, 8.31444955],
       [5.11718415, 6.15920666, 7.50399828],
       [8.35862899, 6.89774308, 9.47737575]])

In [104]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

In [105]:
rand_arr

array([[6.11804718, 5.71857417, 8.3744776 ],
       [9.15738619, 5.80988577, 5.47356536],
       [6.70016617, 8.00441507, 5.76015762],
       [9.55497974, 9.45379358, 6.70185687],
       [5.27453151, 6.7062535 , 7.9722487 ]])

In [106]:
rand_arr = np.random.uniform(5,10, size=(5,3))

In [107]:
rand_arr

array([[8.59460972, 7.91467507, 9.63707655],
       [8.13741354, 9.95218155, 5.63816977],
       [9.57379131, 9.31330016, 7.16443213],
       [7.72680094, 9.74168032, 8.57694579],
       [7.47982563, 7.48134913, 8.4739246 ]])

In [108]:
rand_arr = np.random.random((5,3))

In [109]:
rand_arr

array([[0.35725438, 0.17567361, 0.42238215],
       [0.2657623 , 0.52900553, 0.13067829],
       [0.72196428, 0.21401216, 0.91375677],
       [0.15034813, 0.99210153, 0.55767918],
       [0.61720153, 0.67783877, 0.8406067 ]])

In [110]:
rand_arr = np.random.random([5,3])

In [111]:
rand_arr

array([[0.61096377, 0.43428148, 0.31348456],
       [0.26648174, 0.9690998 , 0.92854644],
       [0.07583477, 0.80595426, 0.68783218],
       [0.68261534, 0.46059905, 0.54045443],
       [0.44470131, 0.8807919 , 0.60687695]])

In [112]:
np.set_printoptions(precision=3)

In [113]:
rand_arr[:4]

array([[0.611, 0.434, 0.313],
       [0.266, 0.969, 0.929],
       [0.076, 0.806, 0.688],
       [0.683, 0.461, 0.54 ]])

In [114]:
# Reset printoptions to default
np.set_printoptions(suppress=False)

In [115]:
np.random.seed(100)

In [116]:
rand_arr = np.random.random([3,3])/1e3

In [117]:
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [118]:
np.set_printoptions(suppress=True, precision=6)

In [119]:
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [126]:
# Limiting the number of items to be printed
np.set_printoptions(threshold=14)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [127]:
# Limiting the number of items to be printed
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [133]:
# full numpy array without truncating
np.set_printoptions(threshold=6)
a = np.arange(15)

In [136]:
# import a dataset with numbers
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [137]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

In [144]:
np.set_printoptions(threshold=1000)

In [145]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [146]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [147]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

(150,)


C:\Users\zahidu\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [148]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [149]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

C:\Users\zahidu\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [150]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [151]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [152]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [153]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [154]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [157]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)

In [158]:
S = (sepallength - Smin)/sepallength.ptp()
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [159]:
# Softmax score computation
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

In [160]:
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [161]:
print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

In [162]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [163]:
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [164]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [165]:
i, j = np.where(iris_2d)

In [166]:
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

In [167]:
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [168]:
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [169]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [170]:
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())

Number of missing values: 
 5


In [171]:
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Position of missing values: 
 (array([ 38,  80, 106, 113, 121], dtype=int64),)


In [172]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [173]:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [174]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [175]:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3]])

In [176]:
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]


array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3]])

In [177]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [178]:
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048718

In [181]:
from scipy.stats.stats import pearsonr  
corr, p_value = pearsonr(iris[:, 0], iris[:, 2])
print(corr)
%time

0.8717541573048713
Wall time: 0 ns


In [182]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [183]:
np.isnan(iris_2d).any()

False

In [184]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [185]:
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [186]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 0. , 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [0. , 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 0. , 0.4],
       [5.1, 3.5, 1.4, 0. ],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0. ],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [0. , 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [187]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [188]:
species = np.array([row.tolist()[4] for row in iris])

In [189]:
species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [190]:
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

In [191]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [192]:
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

In [193]:
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

In [194]:
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [195]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [196]:
# Create a new column for volume
sepallength = arr[:, 0].astype('float')
petallength = arr[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

volume = volume[:, np.newaxis]

out = np.hstack([arr, volume])

In [197]:
out

array([[  0.      ,   1.      ,   2.      ,   0.      ],
       [  3.      ,   4.      ,   5.      ,  47.12389 ],
       [  6.      ,   7.      ,   8.      , 301.592895]])

In [198]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [199]:
# Get the species and petal length columns
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

In [200]:
np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [201]:
# Sort by column position 0: SepalLength
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [202]:
# Find the most frequent value of petal length (3rd column) in iris dataset.
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


In [203]:
# Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50], dtype=int64)

In [204]:
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50], dtype=int64)

In [205]:
# From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

np.clip(a, a_min=10, a_max=30)

print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [206]:
# Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)

print(a.argsort())

[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]


In [207]:
a

array([27.63, 14.64, 21.8 , 42.39,  1.23,  6.96, 33.87, 41.47,  7.7 ,
       29.18, 44.67, 11.25, 10.08,  6.31, 11.77, 48.95, 40.77,  9.43,
       41.  , 14.43])

In [208]:
np.argpartition(-a, 5)[:5]

array([15, 10,  3,  7, 18], dtype=int64)

In [209]:
a[a.argsort()][-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

In [210]:
np.sort(a)[-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

In [211]:
np.partition(a, kth=-5)[-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

In [212]:
a[np.argpartition(-a, 5)][:5]

array([48.95, 44.67, 42.39, 41.47, 41.  ])

In [214]:
np.random.seed(100)

arr = np.random.randint(1,11,size=(6, 10))

arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [215]:
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

In [216]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [217]:
counts_of_all_values_rowwise(arr)

[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [218]:
# Example 2

arr = np.array([np.array(list('bill clinton')), np.array(list('narendramodi')), np.array(list('jjayalalitha'))])
print(np.unique(arr))
counts_of_all_values_rowwise(arr)

[' ' 'a' 'b' 'c' 'd' 'e' 'h' 'i' 'j' 'l' 'm' 'n' 'o' 'r' 't' 'y']


[[1, 0, 1, 1, 0, 0, 0, 2, 0, 3, 0, 2, 1, 0, 1, 0],
 [0, 2, 0, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0],
 [0, 4, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1]]

In [222]:
# Convert array_of_arrays into a flat linear 1d array.

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

# Solution 1
arr_2d = np.array([a for arr in array_of_arrays for a in arr])

# Solution 2:
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


In [223]:
# Compute the one-hot encodings (dummy binary variables for each unique value in the array)

np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [225]:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

In [226]:
one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [227]:
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

In [228]:
# create row numbers grouped by a categorical variable

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [229]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [231]:
# Create groud ids based on a given categorical variable

output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]

output

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [232]:
# Loop example

output = []
uniqs = np.unique(species_small)

for val in uniqs:  # uniq values in group
    for s in species_small[species_small==val]:  # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0]  # groupid
        output.append(groupid)

print(output)

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [233]:
# rank items in an array using numpy

np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)

Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [234]:
# Solution
print(a.argsort().argsort())
print('Array: ', a)

[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [235]:
# Rank items in a multidimensional array using numpy

np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [236]:
print(a.ravel().argsort().argsort().reshape(a.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]
